# Generated by Django 2.2 on 2020-09-16 23:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shipment.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('receiver_name', models.CharField(max_length=250)),
                ('receiver_country', models.CharField(max_length=60)),
                ('receiver_address', models.CharField(max_length=300)),
                ('estimated_shipping_date', models.DateField(null=True)),
                ('scheduled_at', models.DateField(null=True)),
                ('weight', models.FloatField()),
                ('lat', models.DecimalField(decimal_places=8, max_digits=12)),
                ('lon', models.DecimalField(decimal_places=8, max_digits=12)),
                ('tracking_id', models.CharField(default=shipment.models.generate_tracking_id, max_length=35, unique=True)),
                ('state', models.CharField(choices=[('PENDING', 'PENDING'), ('SCHEDULED', 'SCHEDULED'), ('PREPARED', 'PREPARED'), ('DELIVERED', 'DELIVERED')], default='PENDING', max_length=15)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='shipments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('change_shipment_state', 'Can change the status of shipments'), ('print_shipment_labels', 'Can print labels for given shipments'), ('schedule_shipment', 'Can schedule shipments delivery'), ('attach_documents', 'Can attache documents to a shipment'), ('subscribe_webhook', 'Can subscribe to a webhook of an event')],
            },
        ),
        migrations.CreateModel(
            name='ShipmentDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='document')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='shipment.Shipment')),
            ],
        ),
    ]
